# Generated by Django 5.2.18 on 2026-10-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with Errors'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('successful_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with Errors'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='certificates.generationjob')),
            ],
        ),
    ]
